### ISSUE TITLE
DNN 9.2.0

### ISSUE THREAD

**Issue by GitUpA** [redtempo/dnnstuff.injectanything#2]
Feel like getting this working on 9.2?

Method not found: 'System.String[] DotNetNuke.Security.Roles.RoleController.GetRolesByUser(Int32, Int32)'.
   at DNNStuff.InjectAnything.InjectAnything.UserRoles()
   at DNNStuff.InjectAnything.InjectAnything.MakeReplacements(String s)
   at DNNStuff.InjectAnything.InjectAnything.InjectText(String s)
   at DNNStuff.InjectAnything.InjectAnything.Process()
   at DNNStuff.InjectAnything.InjectAnything.Page_Init(Object sender, EventArgs e)

**Comment by richard-edwards** [comment]
They removed a lot of deprecated api's in DNN 9.2 it looks like. I just did a new release to fix that, https://github.com/redtempo/dnnstuff.injectanything/releases/tag/1.5.2
